2018-09-02 00:25:43,715|ERROR|com.jolbox.bonecp.BoneCP|Failed to acquire connection to jdbc:mysql://172.17.20.231:3306/dev_wxpay_nplat?characterEncoding=utf-8. Sleeping for 1000 ms. Attempts left: 10
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 25,079 milliseconds ago.  The last packet sent successfully to the server was 25,079 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3589)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3478)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4019)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:951)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1717)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1276)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2395)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2428)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2213)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:797)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.obtainInternalConnection(BoneCP.java:269)
	at com.jolbox.bonecp.ConnectionHandle.<init>(ConnectionHandle.java:242)
	at com.jolbox.bonecp.PoolWatchThread.fillConnections(PoolWatchThread.java:115)
	at com.jolbox.bonecp.PoolWatchThread.run(PoolWatchThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3039)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3489)
	... 26 common frames omitted
2018-09-02 00:24:26,424|ERROR|o.s.s.s.TaskUtils$LoggingErrorHandler|Unexpected error occurred in scheduled task.
org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Connection reset; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:67)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:212)
	at org.springframework.data.redis.connection.jedis.JedisConnection.sMembers(JedisConnection.java:1986)
	at org.springframework.data.redis.core.DefaultSetOperations$7.doInRedis(DefaultSetOperations.java:129)
	at org.springframework.data.redis.core.DefaultSetOperations$7.doInRedis(DefaultSetOperations.java:126)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:88)
	at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:126)
	at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:91)
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:123)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:398)
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.BinaryJedis.smembers(BinaryJedis.java:1222)
	at org.springframework.data.redis.connection.jedis.JedisConnection.sMembers(JedisConnection.java:1984)
	... 22 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
	... 29 common frames omitted
2018-09-02 00:27:21,095|ERROR|com.jolbox.bonecp.BoneCP|Failed to acquire connection to jdbc:mysql://172.17.20.231:3306/dev_wxpay_nplat?characterEncoding=utf-8. Sleeping for 1000 ms. Attempts left: 10
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1,016 milliseconds ago.  The last packet sent successfully to the server was 1,015 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3589)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3478)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4019)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:951)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1717)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1276)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2395)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2428)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2213)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:797)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.obtainInternalConnection(BoneCP.java:269)
	at com.jolbox.bonecp.ConnectionHandle.<init>(ConnectionHandle.java:242)
	at com.jolbox.bonecp.PoolWatchThread.fillConnections(PoolWatchThread.java:115)
	at com.jolbox.bonecp.PoolWatchThread.run(PoolWatchThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3039)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3489)
	... 26 common frames omitted
2018-09-02 01:42:05,839|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 01:42:05,795|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 04:44:20,259|ERROR|o.s.s.s.TaskUtils$LoggingErrorHandler|Unexpected error occurred in scheduled task.
org.springframework.data.redis.RedisConnectionFailureException: java.net.SocketException: Connection reset; nested exception is redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:67)
	at org.springframework.data.redis.connection.jedis.JedisExceptionConverter.convert(JedisExceptionConverter.java:41)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:37)
	at org.springframework.data.redis.connection.jedis.JedisConnection.convertJedisAccessException(JedisConnection.java:212)
	at org.springframework.data.redis.connection.jedis.JedisConnection.sMembers(JedisConnection.java:1986)
	at org.springframework.data.redis.core.DefaultSetOperations$7.doInRedis(DefaultSetOperations.java:129)
	at org.springframework.data.redis.core.DefaultSetOperations$7.doInRedis(DefaultSetOperations.java:126)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:191)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:153)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:88)
	at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:126)
	at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:91)
	at org.springframework.session.data.redis.RedisSessionExpirationPolicy.cleanExpiredSessions(RedisSessionExpirationPolicy.java:123)
	at org.springframework.session.data.redis.RedisOperationsSessionRepository.cleanupExpiredSessions(RedisOperationsSessionRepository.java:398)
	at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection reset
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:201)
	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:40)
	at redis.clients.jedis.Protocol.process(Protocol.java:141)
	at redis.clients.jedis.Protocol.read(Protocol.java:205)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:297)
	at redis.clients.jedis.Connection.getBinaryMultiBulkReply(Connection.java:233)
	at redis.clients.jedis.BinaryJedis.smembers(BinaryJedis.java:1222)
	at org.springframework.data.redis.connection.jedis.JedisConnection.sMembers(JedisConnection.java:1984)
	... 22 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:127)
	at redis.clients.util.RedisInputStream.ensureFill(RedisInputStream.java:195)
	... 29 common frames omitted
2018-09-02 04:44:27,862|ERROR|com.jolbox.bonecp.ConnectionHandle|Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = 08S01
2018-09-02 04:46:47,540|ERROR|com.jolbox.bonecp.BoneCP|Failed to acquire connection to jdbc:mysql://172.17.20.231:3306/dev_wxpay_nplat?characterEncoding=utf-8. Sleeping for 1000 ms. Attempts left: 10
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 4,944 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3589)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3478)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4019)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:951)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1717)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1276)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2395)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2428)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2213)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:797)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.obtainInternalConnection(BoneCP.java:269)
	at com.jolbox.bonecp.ConnectionHandle.<init>(ConnectionHandle.java:242)
	at com.jolbox.bonecp.PoolWatchThread.fillConnections(PoolWatchThread.java:115)
	at com.jolbox.bonecp.PoolWatchThread.run(PoolWatchThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3039)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3489)
	... 26 common frames omitted
2018-09-02 04:47:38,099|ERROR|com.jolbox.bonecp.BoneCP|Failed to acquire connection to jdbc:mysql://172.17.20.231:3306/dev_wxpay_nplat?characterEncoding=utf-8. Sleeping for 1000 ms. Attempts left: 9
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 4,821 milliseconds ago.  The last packet sent successfully to the server was 4,821 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3589)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3478)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4019)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:951)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1717)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1276)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2395)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2428)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2213)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:797)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.obtainInternalConnection(BoneCP.java:269)
	at com.jolbox.bonecp.ConnectionHandle.<init>(ConnectionHandle.java:242)
	at com.jolbox.bonecp.PoolWatchThread.fillConnections(PoolWatchThread.java:115)
	at com.jolbox.bonecp.PoolWatchThread.run(PoolWatchThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3039)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3489)
	... 26 common frames omitted
2018-09-02 04:48:07,582|ERROR|com.jolbox.bonecp.BoneCP|Failed to acquire connection to jdbc:mysql://172.17.20.231:3306/dev_wxpay_nplat?characterEncoding=utf-8. Sleeping for 1000 ms. Attempts left: 8
com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet successfully received from the server was 1 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
	at sun.reflect.GeneratedConstructorAccessor66.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1116)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3589)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3478)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4019)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:951)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1717)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1276)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2395)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2428)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2213)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:797)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
	at com.jolbox.bonecp.BoneCP.obtainInternalConnection(BoneCP.java:269)
	at com.jolbox.bonecp.ConnectionHandle.<init>(ConnectionHandle.java:242)
	at com.jolbox.bonecp.PoolWatchThread.fillConnections(PoolWatchThread.java:115)
	at com.jolbox.bonecp.PoolWatchThread.run(PoolWatchThread.java:85)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
	at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3039)
	at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3489)
	... 26 common frames omitted
2018-09-02 06:24:00,034|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 06:24:00,046|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 09:00:01,434|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 09:00:00.759 where id='TASK_0004'
2018-09-02 09:00:05,548|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:00:05,549|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:00:08,655|ERROR|com.airb.http.core.SyncClient|Client execute error
org.apache.http.conn.ConnectTimeoutException: Connect to 172.17.20.183:9600 [/172.17.20.183] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.CheckOutInitJob.excute(CheckOutInitJob.java:38)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 19 common frames omitted
2018-09-02 09:00:08,662|ERROR|com.airb.http.core.Http|Execute failed!
org.apache.http.conn.ConnectTimeoutException: Connect to 172.17.20.183:9600 [/172.17.20.183] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.CheckOutInitJob.excute(CheckOutInitJob.java:38)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 19 common frames omitted
2018-09-02 09:00:08,726|ERROR|c.u.service.task.job.CheckOutInitJob|初始化对账失败,日期2018-09-02
2018-09-02 09:00:08,745|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 09:00:08.744 where id='TASK_0004'
2018-09-02 09:10:00,185|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 09:10:00.184 where id='TASK_0003'
2018-09-02 09:10:03,240|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:10:03,257|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:10:06,241|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:10:06,253|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:10:09,254|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:10:09,254|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:10:12,254|ERROR|com.airb.http.core.SyncClient|Client execute error
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.ThirdpartyBillDownJob.excute(ThirdpartyBillDownJob.java:26)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 09:10:12,256|ERROR|com.airb.http.core.Http|Execute failed!
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.ThirdpartyBillDownJob.excute(ThirdpartyBillDownJob.java:26)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 09:10:12,288|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 09:10:12.281 where id='TASK_0003'
2018-09-02 09:15:00,060|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 09:15:00.059 where id='TASK_0011'
2018-09-02 09:15:03,437|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:15:03,437|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:15:06,443|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:15:06,443|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:15:09,462|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 09:15:09,462|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 09:15:12,473|ERROR|com.airb.http.core.SyncClient|Client execute error
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.WangsCashTask.excute(WangsCashTask.java:35)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 09:15:12,474|ERROR|com.airb.http.core.Http|Execute failed!
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.WangsCashTask.excute(WangsCashTask.java:35)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 09:15:12,496|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 09:15:12.493 where id='TASK_0011'
2018-09-02 09:24:42,413|ERROR|com.jolbox.bonecp.ConnectionHandle|Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = 08S01
2018-09-02 10:00:00,194|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 10:00:00.193 where id='TASK_0005'
2018-09-02 10:00:03,424|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 10:00:03,425|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 10:00:06,425|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 10:00:06,426|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 10:00:09,428|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 10:00:09,428|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 10:00:12,427|ERROR|com.airb.http.core.SyncClient|Client execute error
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.TriggerSettleJob.excute(TriggerSettleJob.java:36)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 10:00:12,444|ERROR|com.airb.http.core.Http|Execute failed!
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.TriggerSettleJob.excute(TriggerSettleJob.java:36)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 10:00:12,474|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 10:00:12.474 where id='TASK_0005'
2018-09-02 11:00:00,115|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 11:00:00.111 where id='TASK_0006'
2018-09-02 11:00:03,327|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 11:00:03,327|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 11:00:06,326|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 11:00:06,326|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 11:00:09,327|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 11:00:09,327|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 11:00:12,329|ERROR|com.airb.http.core.SyncClient|Client execute error
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.CreateBillJob.excute(CreateBillJob.java:37)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 11:00:12,348|ERROR|com.airb.http.core.Http|Execute failed!
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.CreateBillJob.excute(CreateBillJob.java:37)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 11:00:12,360|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 11:00:12.359 where id='TASK_0006'
2018-09-02 11:20:46,519|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 11:20:46,524|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 18:24:30,336|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 18:24:30.249 where id='TASK_0012'
2018-09-02 18:24:34,008|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 18:24:34,008|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 18:24:36,984|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 18:24:36,984|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 18:24:40,003|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 18:24:40,004|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 18:24:43,118|ERROR|com.airb.http.core.SyncClient|Client execute error
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.DealerCodeSubMchJob.excute(DealerCodeSubMchJob.java:38)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 18:24:43,118|ERROR|com.airb.http.core.Http|Execute failed!
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.DealerCodeSubMchJob.excute(DealerCodeSubMchJob.java:38)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 18:24:43,126|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 18:24:43.126 where id='TASK_0012'
2018-09-02 18:37:44,700|ERROR|com.jolbox.bonecp.ConnectionHandle|Database access problem. Killing off this connection and all remaining connections in the connection pool. SQL State = 08S01
2018-09-02 19:12:00,278|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=1, last_begin_time=2018-09-02 19:12:00.277 where id='TASK_0013'
2018-09-02 19:12:03,382|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 19:12:03,382|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 19:12:06,384|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 19:12:06,384|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 19:12:09,384|INFO |o.a.http.impl.execchain.RetryExec|I/O exception (java.net.NoRouteToHostException) caught when processing request to {}->http://172.17.20.183:9600: No route to host (Host unreachable)
2018-09-02 19:12:09,384|INFO |o.a.http.impl.execchain.RetryExec|Retrying request to {}->http://172.17.20.183:9600
2018-09-02 19:12:12,386|ERROR|com.airb.http.core.SyncClient|Client execute error
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.BankSubMchUpTask.excute(BankSubMchUpTask.java:31)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 19:12:12,386|ERROR|com.airb.http.core.Http|Execute failed!
java.net.NoRouteToHostException: No route to host (Host unreachable)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.airb.http.core.SyncClient.execute(SyncClient.java:38)
	at com.airb.http.core.Http.execute(Http.java:136)
	at com.airb.http.core.Http.handle(Http.java:75)
	at com.airb.http.core.Http.post(Http.java:70)
	at com.ulopay.service.task.job.BankSubMchUpTask.excute(BankSubMchUpTask.java:31)
	at com.ulopay.service.task.TaskJob.excute(TaskJob.java:75)
	at com.ulopay.service.task.TaskJob.excuteTask(TaskJob.java:51)
	at com.ulopay.service.task.TaskJob.execute(TaskJob.java:29)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2018-09-02 19:12:12,419|DEBUG|c.j.bonecp.PreparedStatementHandle|update scheduler_task set run_state=0, last_end_time=2018-09-02 19:12:12.401 where id='TASK_0013'
2018-09-02 20:28:20,697|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
2018-09-02 20:28:20,697|ERROR|o.s.d.r.l.RedisMessageListenerContainer|Connection failure occurred. Restarting subscription task after 5000 ms
